# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-03 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20171103_0104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'My Subscribers'},
        ),
    ]
