# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-07 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20171104_1710'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductInBasket',
            new_name='ProductInCart',
        ),
        migrations.AlterModelOptions(
            name='productincart',
            options={'verbose_name': 'Product in cart', 'verbose_name_plural': 'Products in cart'},
        ),
    ]
