# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-03 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_image',
            field=models.ImageField(upload_to='static/media/product_images/'),
        ),
    ]
