# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-04 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171103_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_is_active',
            field=models.BooleanField(default=True),
        ),
    ]
